#!/usr/bin/env python3
"""docbuilder - client design documents built on the client's own Word template, written to read as hand-written.

Library:
    from docbuilder import DesignDoc, finalize, check
    d = DesignDoc("Template.docx", "Out.docx")          # keeps cover, TOC, change record, header/footer, styles
    d.replace_text("Document Subtitle", "Network Security Design")   # cover / title boxes
    d.change_record(["23-Sep-2026", "Initial draft", "1.0", "First issue"])
    d.clear_body()                                       # drops the template's sample body from the first Heading 1
    d.h1("Purpose"); d.para("..."); d.bullets([...]); d.table([...], [[...]], [30, 70])
    d.figure("fig.png", "Figure 1: ...", heading="Proposed Architecture")   # landscape page
    d.save()
    pdf = finalize("Out.docx")                           # Word: refresh TOC and fields, export PDF (Windows + Word)
    print(*check("Out.docx", pdf), sep="\n")             # must print nothing before the document is sent

CLI:
    python docbuilder.py finalize <file.docx>
    python docbuilder.py check <file.docx> [--pdf file.pdf] [--banned "word1,word2"]

Text passes through human(): "·" -> comma, " + " -> "and", curly quotes, no inline bold. check() finds what slips
through: dashes, provenance phrases (CLI, read-only, logs show ...), AI vocabulary, arrows or semicolons in prose,
duplicated paragraphs, dangling "Section x.y" references, near-empty pages and stranded table titles.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

from docx import Document
from docx.enum.section import WD_ORIENT, WD_SECTION
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_BREAK
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Cm, Pt, RGBColor

PROSE_STYLES = ("Normal", "List Bullet", "List Bullet 2", "List Paragraph", "Body Text")

# How the facts were gathered never appears in a client document.
PROVENANCE = [r"\bazure cli\b", r"\baz cli\b", r"\bcli\b", r"read-only", r"read only", r"read from azure",
              r"could not be read", r"not readable", r"logs show", r"insights shows", r"setting names",
              r"names only", r"\bpowershell\b", r"\bscript(s|ed)?\b", r"\bclaude\b", r"\bchatgpt\b",
              r"\bgenerated by\b", r"\bas an ai\b", r"\bllm\b"]
# Words that make a document read as machine-written.
AI_VOCAB = [r"\bdelve", r"\bleverag(e|es|ed|ing)\b", r"\bseamless(ly)?\b", r"\brobust\b", r"\bcomprehensive\b",
            r"\bholistic\b", r"\bstreamlin(e|es|ed|ing)\b", r"\bfurthermore\b", r"\bmoreover\b",
            r"it is important to note", r"\butili[sz](e|es|ed|ing)\b", r"\bempower", r"cutting-edge",
            r"state-of-the-art", r"best-in-class", r"game-chang", r"\btapestry\b", r"\bin today's\b",
            r"\bensures? that\b", r"\bpivotal\b", r"\bparamount\b", r"\bunlock", r"\belevat(e|es|ed|ing)\b"]


def human(text: str) -> str:
    """Typeset like a person writing in Word: '·' -> comma, ' + ' -> 'and', curly quotes."""
    t = re.sub(r" · (\.\d[\d.\-]*)", r" (\1)", str(text))      # "pep-x · .66.12" -> "pep-x (.66.12)"
    t = t.replace(" · ", ", ").replace(" + ", " and ")
    t = re.sub(r'(^|[\s(\[])"', "\\1\u201c", t).replace('"', "\u201d")
    t = re.sub(r"(?<=\w)'(?=\w)", "\u2019", t)                    # don't, Microsoft's
    t = re.sub(r"(^|[\s(\[])'", "\\1\u2018", t)                    # opening quote
    return t.replace("'", "\u2019")                                 # closing quote, plural possessive


class DesignDoc:
    """A document built on a client template. Headings, tables and figures reuse the template's own look."""

    def __init__(self, template, out, accent: str | None = None):
        self.doc = Document(str(template))
        self.out = Path(out)
        self.body = self.doc.element.body
        s0 = self.doc.sections[0]
        self.text_w = int((s0.page_width - s0.left_margin - s0.right_margin) / 635)   # EMU -> dxa
        h1c = self.doc.styles["Heading 1"].font.color
        self.accent = accent or (str(h1c.rgb) if h1c is not None and h1c.type is not None and h1c.rgb else "1F4E79")
        names = {s.name for s in self.doc.styles}
        self.bullet_style = next((n for n in ("List Bullet 2", "List Bullet") if n in names), "Normal")
        self.cell_style = "NormTable" if "NormTable" in names else "Normal"
        for name, size in (("Heading 2", 13), ("Heading 3", 11.5)):      # every heading level in the accent colour
            if name in names:
                st = self.doc.styles[name]
                st.font.color.rgb = RGBColor.from_string(self.accent)
                st.font.size = Pt(size)
        if self.bullet_style != "Normal":                                 # bullets use the body font, not Arial
            self.doc.styles[self.bullet_style].font.name = None
            self.doc.styles[self.bullet_style].font.size = None

    # ---------------- template parts ----------------
    def replace_text(self, old: str, new: str) -> int:
        """Replace text anywhere in the body, including cover text boxes. Returns the number of replacements."""
        n = 0
        for t in self.body.iter(qn("w:t")):
            if t.text and old in t.text:
                t.text = t.text.replace(old, new)
                n += 1
        return n

    def change_record(self, values: list[str]):
        """Fill the first empty row of the template's Change Record table and keep the table on one page."""
        tbl = next((t for t in self.doc.tables if "change record" in t.rows[0].cells[0].text.lower()), None)
        if tbl is None:
            return None
        start = next((i for i, r in enumerate(tbl.rows) if r.cells[0].text.strip().lower() == "date"), 1) + 1
        row = next((r for r in tbl.rows[start:] if not "".join(c.text for c in r.cells).strip()), tbl.rows[start])
        for cell, val in zip(row.cells, values):
            runs = cell.paragraphs[0].runs or [cell.paragraphs[0].add_run()]
            runs[0].text = human(val)
            rf = runs[0]._r.get_or_add_rPr().get_or_add_rFonts()
            for a in ("w:asciiTheme", "w:hAnsiTheme", "w:cstheme"):
                rf.set(qn(a), "minorHAnsi")
            for r in runs[1:]:
                r.text = ""
        for r in tbl.rows[:-1]:
            for c in r.cells:
                for p in c.paragraphs:
                    p.paragraph_format.keep_with_next = True
        return tbl

    def clear_body(self):
        """Remove the template's sample content from its first Heading 1 onwards (the final sectPr stays)."""
        first = next((p for p in self.doc.paragraphs if p.style.name == "Heading 1"), None)
        el = first._p if first is not None else None
        while el is not None:
            nxt = el.getnext()
            if el.tag != qn("w:sectPr"):
                self.body.remove(el)
            el = nxt

    # ---------------- content ----------------
    def _runs(self, p, text):
        label = text.startswith("**") and text.endswith("**") and text.count("**") == 2
        r = p.add_run(human(text.replace("**", "")))
        r.bold = label or None
        return p

    def h1(self, text):
        return self.doc.add_paragraph(text, style="Heading 1")

    def h2(self, text):
        return self.doc.add_paragraph(text, style="Heading 2")

    def h3(self, text):
        return self.doc.add_paragraph(text, style="Heading 3")

    def para(self, text, justify=True):
        """Body paragraph. Only a paragraph written entirely as **Label** is bold; inline ** is dropped."""
        p = self._runs(self.doc.add_paragraph(style="Normal"), text)
        if justify:
            p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        return p

    def bullets(self, items):
        for it in items:
            self._runs(self.doc.add_paragraph(style=self.bullet_style), it)

    def _cell(self, cell, text, width, header=False, fill=None, size=9.5):
        tcPr = cell._tc.get_or_add_tcPr()
        tcW = tcPr.find(qn("w:tcW"))
        if tcW is None:
            tcW = OxmlElement("w:tcW")
            tcPr.append(tcW)
        tcW.set(qn("w:w"), str(width))
        tcW.set(qn("w:type"), "dxa")
        if fill:
            shd = OxmlElement("w:shd")
            for k, v in (("val", "clear"), ("color", "auto"), ("fill", fill)):
                shd.set(qn(f"w:{k}"), v)
            tcPr.append(shd)
        p = cell.paragraphs[0]
        p.style = self.doc.styles[self.cell_style]
        if self.cell_style == "Normal":
            p.paragraph_format.space_after = Pt(2)
        for i, line in enumerate(human(str(text).replace("**", "")).split("\n")):
            if i:
                p.add_run().add_break(WD_BREAK.LINE)
            if not line:
                continue
            r = p.add_run(line)
            r.font.size = Pt(size)
            rf = r._r.get_or_add_rPr().get_or_add_rFonts()
            for a in ("w:ascii", "w:hAnsi", "w:cs"):
                rf.attrib.pop(qn(a), None)
            for a in ("w:asciiTheme", "w:hAnsiTheme", "w:cstheme"):
                rf.set(qn(a), "minorHAnsi")
            if header:
                r.bold = True
                r.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

    def table(self, headers, rows, widths, title=None, size=9.5):
        """Accent-coloured header row (and optional title row), grey hairlines, fixed column widths in ratio `widths`.
        Title and header rows repeat on each page and stay with the first data row. A lead-in paragraph just before
        the table that ends with ':' is kept on the same page as the table."""
        prev = self.doc.paragraphs[-1] if self.doc.paragraphs else None
        if prev is not None and prev.text.rstrip().endswith(":"):
            prev.paragraph_format.keep_with_next = True
        widths = [int(w * self.text_w / sum(widths)) for w in widths]
        t = self.doc.add_table(rows=0, cols=len(headers))
        tblPr = t._tbl.tblPr
        tblW = OxmlElement("w:tblW")
        tblW.set(qn("w:w"), str(self.text_w))
        tblW.set(qn("w:type"), "dxa")
        tblPr.append(tblW)
        borders = OxmlElement("w:tblBorders")
        for side in ("top", "left", "bottom", "right", "insideH", "insideV"):
            b = OxmlElement(f"w:{side}")
            for k, v in (("val", "single"), ("sz", "2"), ("space", "0"), ("color", "C0C0C0")):
                b.set(qn(f"w:{k}"), v)
            borders.append(b)
        tblPr.append(borders)
        layout = OxmlElement("w:tblLayout")
        layout.set(qn("w:type"), "fixed")
        tblPr.append(layout)
        for gc, w in zip(t._tbl.tblGrid.findall(qn("w:gridCol")), widths):
            gc.set(qn("w:w"), str(w))
        if title:
            row = t.add_row()
            c = row.cells[0].merge(row.cells[-1])
            self._cell(c, title, self.text_w, header=True, fill=self.accent, size=size)
        hdr = t.add_row()
        hdr._tr.get_or_add_trPr().append(OxmlElement("w:tblHeader"))
        for c, h, w in zip(hdr.cells, headers, widths):
            self._cell(c, h, w, header=True, fill=self.accent, size=size)
        for r in t.rows:
            for c in r.cells:
                for p in c.paragraphs:
                    p.paragraph_format.keep_with_next = True
        for values in rows:
            row = t.add_row()
            for c, v, w in zip(row.cells, values, widths):
                self._cell(c, v, w, size=size)
        self.doc.add_paragraph(style="Normal")
        return t

    def caption(self, text):
        name = "Caption" if "Caption" in {s.name for s in self.doc.styles} else "Normal"
        p = self.doc.add_paragraph(human(text), style=name)
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        return p

    def new_section(self, landscape: bool):
        """Next page as landscape or portrait, same header/footer. A trailing blank line is removed first so the
        break never leaves an empty page behind."""
        last = self.body[-2] if self.body[-1].tag == qn("w:sectPr") else self.body[-1]
        if (last.tag == qn("w:p") and not "".join(last.itertext()).strip()
                and last.find(qn("w:pPr") + "/" + qn("w:sectPr")) is None):
            self.body.remove(last)
        s = self.doc.add_section(WD_SECTION.NEW_PAGE)
        s.different_first_page_header_footer = False
        if landscape != (s.page_width > s.page_height):
            s.page_width, s.page_height = s.page_height, s.page_width
        s.orientation = WD_ORIENT.LANDSCAPE if landscape else WD_ORIENT.PORTRAIT
        return s

    def figure(self, path, caption, heading=None, note=None, after=None, width_cm=None):
        """A diagram on its own landscape page: optional section heading, image, caption, note, then `after()`
        (e.g. a short table that explains the figure). Returns to portrait afterwards."""
        s = self.new_section(True)
        if heading:
            self.h1(heading)
        usable = (s.page_width - s.left_margin - s.right_margin) / 360000          # EMU -> cm
        p = self.doc.add_paragraph(style="Normal")
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p.paragraph_format.space_after = Pt(0)
        p.add_run().add_picture(str(path), width=Cm(width_cm or usable - 0.3))
        self.caption(caption)
        if note:
            self.para(note)
        if after:
            after()
        self.new_section(False)

    def save(self):
        for s in self.doc.sections[1:]:
            s.different_first_page_header_footer = False
        self.doc.save(str(self.out))
        return self.out


# ---------------- Word: refresh TOC and fields, export PDF ----------------
_PS = r"""
$w = New-Object -ComObject Word.Application; $w.Visible = $false
try {
  $d = $w.Documents.Open($env:DOCB_SRC)
  foreach ($t in $d.TablesOfContents) { $t.Update() }
  $d.Fields.Update() | Out-Null
  $d.Save()
  if ($env:DOCB_PDF) { $d.ExportAsFixedFormat($env:DOCB_PDF, 17) }
  "pages: " + $d.ComputeStatistics(2)
  $d.Close($false)
} finally { $w.Quit() }
"""


def finalize(docx, pdf=True) -> str | None:
    """Open the document in Word to refresh the TOC and fields, save, and export a PDF next to it.
    Needs Windows with Microsoft Word; elsewhere prints a note and returns None (update the TOC by hand)."""
    src = Path(docx).resolve()
    out = src.with_suffix(".pdf") if pdf else None
    if os.name != "nt":
        print("finalize: Word automation needs Windows; open the file in Word and update the table of contents")
        return None
    env = dict(os.environ, DOCB_SRC=str(src), DOCB_PDF=str(out) if out else "")
    r = subprocess.run(["powershell", "-NoProfile", "-Command", _PS], env=env, capture_output=True, text=True, timeout=600)
    print((r.stdout or r.stderr).strip())
    return str(out) if out and out.exists() else None


# ---------------- checks ----------------
def _heading_numbers(doc):
    """Numbers Word will show for Heading 1/2 (assumes the template numbers them 1, 1.1 ...)."""
    nums, h1n, h2n, started = set(), 0, 0, False
    for p in doc.paragraphs:
        if p.style.name == "Heading 1":
            started = True
            h1n, h2n = h1n + 1, 0
            nums.add(str(h1n))
        elif p.style.name == "Heading 2" and started:
            h2n += 1
            nums.add(f"{h1n}.{h2n}")
    return nums


def check(docx, pdf=None, banned=()) -> list[str]:
    """Everything that makes a client document look machine-made or leaks how it was produced. Empty list = clean."""
    doc = Document(str(docx))
    issues = []
    prose = [p for p in doc.paragraphs if p.style.name in PROSE_STYLES and p.text.strip()]
    cells = [c.text for t in doc.tables for r in t.rows for c in r.cells]
    everything = [p.text for p in doc.paragraphs] + cells
    text = "\n".join(everything)

    for ch, name in (("\u2014", "em dash"), ("\u2013", "en dash"), ("\u00b7", "middle dot '·'"), ("'", "straight apostrophe"),
                     ('"', "straight double quote"), ("\u2026", "ellipsis character")):
        n = text.count(ch)
        if n:
            issues.append(f"punctuation: {n} x {name}")
    if re.search(r"\w \+ \w", text):
        issues.append("punctuation: ' + ' used as 'and'")
    for p in prose:
        if any(ch in p.text for ch in ("\u2192", "\u2190", "=>", "->")):
            issues.append(f"arrow in prose: {p.text[:70]!r}")
        if ";" in p.text:
            issues.append(f"semicolon in prose: {p.text[:70]!r}")
        runs = [r for r in p.runs if r.text.strip()]
        if any(r.bold for r in runs) and not all(r.bold for r in runs):
            issues.append(f"inline bold or bold lead-in: {p.text[:70]!r}")
    low = text.lower()
    for rx in PROVENANCE + [re.escape(b.strip().lower()) for b in banned if b.strip()]:
        for m in sorted({m.group(0) for m in re.finditer(rx, low)}):
            issues.append(f"provenance/banned wording: '{m}'")
    for rx in AI_VOCAB:
        for m in sorted({m.group(0) for m in re.finditer(rx, low)}):
            issues.append(f"AI-sounding word: '{m}'")
    seen = Counter(p.text.strip()[:80].lower() for p in prose if len(p.text.strip()) > 40)
    for k, n in seen.items():
        if n > 1:
            issues.append(f"repeated paragraph ({n}x): {k[:60]!r}")
    nums = _heading_numbers(doc)
    for ref in sorted(set(re.findall(r"Sections? (\d+(?:\.\d+)?)(?: and (\d+(?:\.\d+)?))?", text))):
        for r in filter(None, ref):
            if r not in nums:
                issues.append(f"reference to Section {r}, which has no heading")

    if pdf and Path(pdf).exists():
        try:
            import pymupdf
        except ImportError:
            issues.append("pdf checks skipped: pip install pymupdf")
        else:
            pdoc = pymupdf.open(str(pdf))
            pages = [[l.strip() for l in p.get_text().splitlines() if l.strip()] for p in pdoc]
            common = Counter(l for pg in pages for l in set(pg))
            repeating = {l for l, n in common.items() if n > max(2, len(pages) // 2)}     # header / footer lines
            for i, (pg, page) in enumerate(zip(pages, pdoc), 1):
                content = [l for l in pg if l not in repeating and not re.fullmatch(r"(Page\s*\|?\s*)?\d+", l)]
                has_image = bool(page.get_images())
                if i > 1 and not has_image and len(content) <= 1:
                    issues.append(f"page {i} is empty or holds only {content or 'a header and footer'}")
                if content and re.match(r"^Table \d+[:.]", content[-1]):
                    issues.append(f"page {i} ends with a table title separated from its table: {content[-1]!r}")
                if content and not has_image and re.match(r"^Figure \d+[:.]", content[0]):
                    issues.append(f"page {i} starts with a figure caption that spilled from its image: {content[0]!r}")
    return issues


if __name__ == "__main__":
    if len(sys.argv) < 3 or sys.argv[1] not in ("finalize", "check"):
        sys.exit(__doc__)
    if sys.argv[1] == "finalize":
        finalize(sys.argv[2])
        sys.exit(0)
    args = sys.argv[3:]
    pdf_arg = args[args.index("--pdf") + 1] if "--pdf" in args else None
    banned_arg = args[args.index("--banned") + 1].split(",") if "--banned" in args else ()
    found = check(sys.argv[2], pdf_arg, banned_arg)
    print("\n".join(found) if found else "check: clean")
    sys.exit(1 if found else 0)
