// Generated by scripts/build-content.mjs before every dev and build.
import data from '../.generated/content.json'

export type Section = { heading: string; slug: string; html: string }
export type Gallery = { title: string; note: string; prompts: string[] }
export type Skill = {
  pkg: string
  slug: string
  title: string
  name: string
  version: string
  description: string
  summary: string
  install: string
  repo: string
  npm: string
  intro: string
  sections: Section[]
  changelog: string
  skill: string
  prompt: string
  gallery: Gallery[]
  downloads: number | null
}
export type Agent = { id: string; label: string; path: string }

// Typed assignment, not `as`: a field missing from the JSON is a type error here.
export const skills: Skill[] = data.skills
export const agents: Agent[] = data.agents
export const getSkill = (slug: string) => skills.find((s) => s.slug === slug)
