// Generated by scripts/build-content.mjs before every dev and build.
import data from '../.generated/content.json'

export type Section = { heading: string; slug: string; html: string }
export type Skill = {
  pkg: string
  slug: string
  title: string
  name: string
  version: string
  description: string
  summary: string
  install: string
  repo: string
  npm: string
  intro: string
  sections: Section[]
  changelog: string
  skill: string
}
export type Agent = { id: string; label: string; path: string }

export const skills = data.skills as Skill[]
export const agents = data.agents as Agent[]
export const getSkill = (slug: string) => skills.find((s) => s.slug === slug)
